
import React from 'react';
import './PrivacyPage.css';

import BasePage from '../BasePage';


function PrivacyPage(props) {
	return (
		<BasePage className="privacy-page-wrapper">
			<h1>Legal</h1>
			<div className="privacy-page-text">
				<div>
					<p>We only collect data that can be directly used to improve your product experience. Every piece of data we collect, from your company name to the number of adjectives you use, is collected with specific intentions. We use data to improve our predictive models, so that the more you use Design Engine's products, the better results you get. We aggregate data into patterns to provide smarter writing guidance over time. We don't sell your data. We are committed to making Design Engine so useful that it is an indispensable part of your company's operations and productivity. We store your document text in order to understand company and industry language patterns, but we will not share your data with anyone outside your company or ours, except for trusted third-party services providers that support us in providing our services to you. We are committed to the security of your private data. Privacy and security go hand in hand. Our commitment to your privacy means that we also take the security of your data seriously. We take steps to ensure that your Personal Information is treated securely and in accordance with this Privacy Policy. In this document, Design Engine refers to the products and services that we offer at https://designengine.ai/ (&ldquo;Service&rdquo; or &ldquo;Services&rdquo;). It also refers to our company, Design Engine AI, Inc., as &ldquo;Design Engine,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us.&rdquo;</p>
					<p>Data We Collect We collect data at different points during your use of Design Engine. We always strive to be open with you about the data we collect and how we're using it. When you inquire about or purchase our Services, we may require you to provide Personal Information, such as:</p>
					<p>Name Business contact information (email address, mailing address, and phone number) We want Design Engine to be easy to use, so in addition to Personal Information, we collect data about your document source and format. We also collect data about how you engage with Design Engine's phrase highlights, tooltips, charts, text formatting, and other product options. That helps us know which areas of the product are most useful to you.</p>
					<p>We also collect information about the text you are optimizing, including the text, scores, metadata, and editorial changes that you make in response to Design Engine's suggestions.</p>
					<p>We also automatically collect some log data. This may include your IP address, as well as your web browser, operating system, and other attributes of your system that are captured by Google Analytics. As you navigate our web sites and use our Services, we may collect information such as session duration through cookies, pixel tags, local storage, web beacons, or other technologies (&ldquo;Technologies&rdquo;).</p>
					<p>If you would like to opt-out of the Technologies we employ on our web sites or Services, you may do so by blocking, deleting, or disabling them as your web browser or device permits.</p>
					<p>What We Do with Data Data we collect is used to improve all aspects of our product experience and to provide the services requested. For example:</p>
					<p>We use engagement data to improve our in-product experience, including the quality of our recommendations, our predictive models, and the options that we offer for usage. We want our user experience to delight you. We use log and engagement data to keep our service secure and reliable, and to quickly investigate failures and disruptive patterns. We want our customer experience to be reliable and trustworthy. We use your account and engagement information to communicate with you better. We want all our customer communication, whether email, in-product, or other channels, to be relevant and helpful. Some companies choose to share outcomes data with Design Engine in order to get a customized predictive model that is exactly tailored for their purposes. For companies that share this data, in addition to including it in Design Engine's anonymized and aggregate models, we will store this and use it to build a model specifically for your company. We use this data to drive continuous improvements to our models. Additionally, we use Personal Information to:</p>
					<p>Send you the information you requested Respond to your customer service requests Send newsletters or marketing communications Respond to questions and concerns Improve our web site and marketing efforts Conduct research and analysis Communicate with you electronically regarding security, privacy, and administrative issues, including system outages or breaches Respond to inquiries regarding career opportunities We store Personal Information collected anywhere in the world, including but not limited to the United States (&ldquo;US&rdquo;), the European Union (&ldquo;EU&rdquo;), in the cloud, on our servers, or the servers of our service providers. Your Personal Information may be accessible to law enforcement or other authorities pursuant to a lawful request. By providing Personal Information to Design Engine, you consent to any transfer and Processing of your Personal Information in accordance with this Policy.</p>
					<p>Data We Share We may share your Personal Information as described in this Privacy Policy (e.g. with our third-party service providers; to comply with legal obligations; to protect and defend our rights and property; to pursue legitimate business purposes) or with your permission.</p>
					<p>We will not sell Personal Information or broadly disclose any data about your usage patterns except in an aggregated and non-identifiable way. If your employer is a Design Engine corporate subscriber, we will share aggregated usage data with your employer.</p>
				</div>

				<h6 style={{ marginBottom : '4px' }}>Additionally, we share Personal Information as follows:</h6>
				<div>
					<p>Vendors and Service Providers: We may share Personal Information with vendors and service providers in connection with the provision of the web site and Services. We execute contracts with vendors and service providers to explicitly require them to adhere to our privacy and customer data handling policies. To see a list of our sub-processors, please email us at privacy@Design Engine.com. As Required by Law: We may access, preserve, and disclose your Personal Information as required by law. In addition, from time to time, server logs may be reviewed for security purposes—e.g. to detect unauthorized activity on the Services. In such cases, server log data containing IP addresses may be shared with law enforcement bodies in order that they may identify users in connection with their investigation of the unauthorized activities. Merger, Sale, or Other Asset Transfers: If we are involved in a merger, acquisition, or other financial restructuring, your Personal Information may be sold or transferred as part of the transaction as permitted by law and/or contract. Your Personal Information Rights Right to Opt Out You have the right to opt out of certain uses and disclosures of your Personal Information. Where you have consented to our processing of your Personal Information, you may withdraw that consent at any time and opt-out to further processing by contacting privacy@Design Engine.com.</p>
					<p>If you receive an unwanted email from us, you can use the unsubscribe link found at the bottom of the email to opt-out of receiving future emails. We will process your request within a reasonable time after receipt. Note that you will continue to receive transaction-related emails regarding products or services you have requested. We may also send you certain non-promotional communications regarding Design Engine and our Services and you will not be able to opt out of those communications.</p>
					<p>We maintain telephone &ldquo;do-not-call&rdquo; and &ldquo;do-not-mail&rdquo; lists as mandated by law. We process requests to be placed on do-not-mail, do-not-phone and do-not-contact lists within 60 days after receipt, or such shorter time as may be required by law.</p>
					<p>Rights of Access, Rectification, Erasure, and Restriction You may ask whether we are processing Personal Information about you, request access to your Personal Information, and ask that we correct, amend, or delete your Personal Information where it is inaccurate. To do this, send an email to privacy@Design Engine.com. Please include your full name, the email address associated with your account, and a detailed description of your data request. Such requests will be processed in line with local laws.</p>
					<p>If you are an employee of one of our customers and would like to access, correct, amend, or delete your Personal Information from our service, please contact your employer directly. If a customer (i.e. your employer) requests our assistance in responding to their employees' requests, we will respond to such requests within 20 business days.</p>
					<p>We will make good faith efforts to provide you with access to your Personal Information, but there may be circumstances in which we are unable to do so. If we determine that access may not be granted, we will provide you with an explanation of why that determination has been made and a contact point for any further inquiries. To protect your privacy, we will take commercially reasonable steps to verify your identity before granting access to or making any changes to your Personal Information.</p>
					<p>Other Terms Privacy Policy Changes This Privacy Policy is subject to the terms in our Terms of Service, available for review at https://designengine.ai/terms-of-service/. In some cases, our customers have signed a Master Services Agreement with us. Our Terms of Service, or a signed Master Services Agreement, take precedence over any conflicting provision in this Privacy Policy.</p>
					<p>We reserve the right to change this Privacy Policy and will post any revisions on our web site.</p>
					<p>We encourage you to review this Privacy Policy regularly for any changes. Your continued use of our web site or Services after any changes have been made acts as your consent to the changes. If there are any material changes to this Privacy Policy, we will notify you as required by applicable law and will post any adjustments to the Privacy Policy on this web page. The revised version will be effective immediately when it is posted.</p>
					<p>Additionally, before we use Personal Information for any new purpose not originally authorized by you, we will provide information regarding the new purpose and give you the opportunity to opt-out.</p>
					<p>If at any point you do not agree to any portion of the Privacy Policy then in effect, you must immediately stop using the Services.</p>
					<p>Data Retention We will retain Personal Information (including data we collect on behalf of our customers) as described in this Privacy Policy for as long as is needed to provide you Services, and as necessary to comply with our legal obligations, resolve disputes, establish legal defenses, conduct audits, pursue legitimate business purposes, enforce our agreements, or to comply with applicable law.</p>
					<p>Jurisdiction By using the web site, we will transfer data to the United States, a jurisdiction outside of the EU. By choosing to visit the web site, utilize the Services, or otherwise provide data to us, you agree that any dispute over privacy or the terms contained in this Privacy Policy will be governed by the laws of the state of Washington in the US and the adjudication of any disputes arising in connection with us or the web site will be in accordance with the Terms.</p>
					<p>Change Your Password If you would like to update or change your password, click on the &ldquo;Forgot your password?&rdquo; link on the Sign in screen. We will send a link via email that will enable you to change your password.</p>
					<p>If your company uses Single Sign-On (SSO) to sign in to Design Engine, you will not be able to change your password from within Design Engine. Contact your company's administrator for information on changing your SSO password in accordance with company security policies.</p>
					<p>Children's Privacy Services are not directed to nor does Design Engine knowingly collect Personal Information from children under 13 years of age. If you learn that your child has provided us with Personal Information without your consent, you may alert us at privacy@Design Engine.com. If we learn that we have collected any Personal Information from children under 13, we will promptly take steps to delete such Personal Information and terminate the child's account.</p>
					<p>California Privacy Rights California law permits users who are California residents to request and obtain from us once a year, free of charge, a list of the third parties to whom we have disclosed their Personal Information (if any) for their direct marketing purposes in the prior calendar year, as well as the type of Personal Information disclosed to those parties. We do not share Personal Information with third parties for their own marketing purposes.</p>
				</div>
			</div>
		</BasePage>
	);
}


export default (PrivacyPage);
