
export const OVERLAY_TYPE_AUTO_SCROLL = 'OVERLAY_TYPE_AUTO_SCROLL';
export const OVERLAY_TYPE_AUTO_SIZE = 'OVERLAY_TYPE_AUTO_SIZE';
export const OVERLAY_TYPE_POSITION_OFFSET = 'OVERLAY_TYPE_POSITION_OFFSET';
export const OVERLAY_TYPE_PERCENT_SIZE = 'OVERLAY_TYPE_PERCENT_SIZE';

export { default } from './BaseOverlay';
