
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const DEVICES_LOADED = 'DEVICES_LOADED';
export const COMPONENT_TYPES_LOADED = 'COMPONENT_TYPES_LOADED';
export const EVENT_GROUPS_LOADED = 'EVENT_GROUPS_LOADED';

export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const TEAM_LOADED = 'TEAM_LOADED';
export const BUILD_PLAYGROUNDS_LOADED = 'BUILD_PLAYGROUNDS_LOADED';
export const TYPE_GROUP_LOADED = 'TYPE_GROUP_LOADED';
export const TEAM_BUILDS_LOADED = 'TEAM_BUILDS_LOADED';
export const PLAYGROUND_LOADED = 'PLAYGROUND_LOADED';
export const TEAM_COMMENTS_LOADED = 'TEAM_COMMENTS_LOADED';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED';

export const SET_TEAM = 'SET_TEAM';
export const SET_PLAYGROUND = 'SET_PLAYGROUND';
export const SET_TYPE_GROUP = 'SET_TYPE_GROUP';
export const SET_DEVICE = 'SET_DEVICE';
export const SET_COMPONENT = 'SET_COMPONENT';
export const SET_COMMENT = 'SET_COMMENT';
export const SET_INVITE = 'SET_INVITE';

export const SET_REDIRECT_URI = 'SET_REDIRECT_URI';
export const UPDATE_MATCH_PATH = 'UPDATE_MATCH_PATH';

export const TOGGLE_AX = 'TOGGLE_AX';
export const TOGGLE_COMMENTS = 'TOGGLE_COMMENTS';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const UPDATE_MOUSE_COORDS = 'UPDATE_MOUSE_COORDS';
