
export const ADD_FILE_UPLOAD = 'ADD_FILE_UPLOAD';
export const APPEND_EXPLORE_ARTBOARDS = 'APPEND_EXPLORE_ARTBOARDS';
export const APPEND_UPLOAD_ARTBOARDS = 'APPEND_UPLOAD_ARTBOARDS';

export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';

export const UPDATE_NAVIGATION = 'UPDATE_NAVIGATION';

export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED';
