
export const ADD_ARTICLE = 'ADD_ARTICLE';

export const APPEND_EXPLORE_ARTBOARDS = 'APPEND_EXPLORE_ARTBOARDS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED';