
export const COMPONENT_MENU_ITEM_COPY = 'COMPONENT_MENU_ITEM_COPY';
export const COMPONENT_MENU_ITEM_AUTHOR = 'COMPONENT_MENU_ITEM_AUTHOR';
export const COMPONENT_MENU_ITEM_COMMENTS = 'COMPONENT_MENU_ITEM_COMMENTS';

export { default } from './ComponentMenu';
